name: DevOps CI Pipeline

on:
  push:
    branches:
      - main

jobs:

  validate:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Create ENV
        run: |
          echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" > backend/.env
          echo "ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}" >> backend/.env

      - name: Build Containers
        run: |
          docker compose build

      - name: Validate Compose
        run: |
          docker compose config